global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton_voronov'
