version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UIVER}
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      - fron_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
#    build: ./post-py
    image: ${USERNAME}/post:${POSTVER}
    networks:
      - back_net
      - fron_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${COMVER}
    networks:
      - back_net
      - fron_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.2.0/24"
  fron_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.1.0/24"
